language: ruby
sudo: required
before_script:
   - chmod +x ./_scripts/build.sh
rvm:
  - 2.3.3
branches:
  except:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: qCzRT8SEKjzyU/u/ceukF6EsLWxkdLGN+gj1ENEiBOVoVmNLH+Gg5aDJ0uObRMHSnbXnlWbhyoeJ4cZqv5/tZDo/tyb386lP4S5kVPZvHKawb1pEzgKY3pKcfV9wGzxwJSPLGbrBte6KCEt0ZUOdRyevum/u+QfISh97Hpci9+dw3A7sCOVj0J8LQkfTB51e4/KPw5ao5uAi4tZ2oA2x0x1ln+pNpislgzFs/0kq5E8s6fyxJ1GSKTslW+hBXImZn7YneimzMMXgH5sREkmljXBa+GDu2R00T1RYOO5ELLB5MhdM70rfj8Vp5KHqUsyAsS8nZntVyNJn7A2iPVrRSRu+PZTiOOO5qegI2idVgB5+pMMFmQLRkuhIn10L9Jb7Vr3ZY+hzcz8YuTjioGETjXQ254Sw1UAijzw7va4uMyMQuP3TUz6fbfXBddOVpsJFJcKcUIZAk6eibZXGD2StVqN/YYJlXTOVOKkvNxPP+0vQOkEcdxrY07ZD6blEs2kqnxpTaEHGXHPr81Q7zQvXgvFYzmavWmuH8ICirnftF0MsfPcYCrmhPWe3rni9qVRHfhOdSw2uc2fhfzas2gcWYD7NUWeLdtZo6kDnvgwCn7NqrnXfBnGhMYLEN+X9Nz9OK6+x87VT5VQQwsqMMWv6wiQwb6eGCSncbdGB08d1DjY=
  - secure: IjfdmSOR2qKMzMAn4L3w4HVb4YCfDWq0B1DdCg6/AS9hgCilF0fUZX06VrlIaZuIhWk1+5YpPNEh/XTj19LqhosKrzb9V+vZs5SJ2kb5eML0u7goGV8Sz497yt/oiaFQKlVZlRA1qp2Y+IiezEZE8PGmWa81Ywh6CKHbgGnEmOz9jef7ZPtae3IWNUh5CDTnLOaIPfU2eyi8EpPePzgPpYZfh6fM2FmDju8AD3aHKrpKJGa6IPSP80c/3qpp8kPig94OaYaGG8LtcFMgXEbGzd9kxZILj1zjpgttZTc5FvibgWRSoAUpXqgfwi3u3nImcMz4KQXjKUo3Knvq4uT2QLliq7zQUr9cZjfFsLuvUpuw5aNzpHDtaLY5GU/yszAJCZE0o8MswAvB6GZIir5ViluphLTgr5VEyh26xonsJeVgoq6YDdB9mQ+lmaTfUQWNY2ROAg/UtsJbagnshShCANQkXyDvIDa/jMyH1lnnBUuIl5imQ0rP6xIG6ZkJQNbQFGaz+uqmP3DvD4G0mT1Jhn+xzQaPE0wftem0X3aMW2bWTqMvAJ+6ShLziON+i4QDBbnp4jd19c5H/d5vmiTDrtG9Y27r3SwoViACj0hp1uaO4GSeYKBhf2EcAkcGB/6I8RO6aCOyDEnOxc1PMzc+UNahGmI/MsM0WTbjKJJ6Ph0=
deploy:
  provider: script
  script: "./_scripts/build.sh"
  skip_cleanup: true
  on:
    branch: source
