# Site settings
title: Benoît Verhaeghe
header-img: img/home-bg.jpg
email: badetitou@gmail.com
copyright_name: badetitou
description: "Presentation of Benoît \"badetitou\" Verhaeghe"
baseurl: ""
url: "http://badetitou.github.io"
twitter_username: badetitou
github_username:  badetitou
facebook_username:  badetitou
email_username:  badetitou@gmail.com
linkedin_username: benoitverhaeghe

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id: UA-112714614-1

collections:
  tps:
    output: true
  teachings:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-scholar

# Reveal.js subdirectory
reveal_path: /reveal.js/

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: /reveal.js/css/theme/ 

# Additional custom CSS paths
extra_css: 

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet: /reveal.js/lib/css/zenburn.css

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 

# Additional reveal.js dependencies
reveal_dependencies: 

scholar:
  bibliography_template: bib
  sort_by: year
  order: descending
  group_by: type

defaults:
  -
    scope:
      path: ""
    values:
      layout: reveal
      reveal:
        controls: true
        progress: true
        slideNumber: false
        history: true
        keyboard: true
        overview: true
        center: true
        touch: true
        loop: false
        rtl: false
        fragments: true
        embedded: false
        autoSlide: false
        autoSlideStoppable: true
        mouseWheel: false
        hideAddressBar: true
        previewLinks: false
        transition: fade
        transitionSpeed: default
        backgroundTransition: default
        viewDistance: 3
        parallaxBackgroundImage:
        parallaxBackgroundSize:
        theme: night.css