# Site settings
title: Benoît Verhaeghe
header-img: img/home-bg.jpg
email: badetitou@gmail.com
copyright_name: badetitou
description: "Presentation of Benoît \"badetitou\" Verhaeghe"
baseurl: ""
url: "http://badetitou.github.io"
twitter_username: badetitou
github_username:  badetitou
facebook_username:  badetitou
email_username:  badetitou@gmail.com
linkedin_username: benoitverhaeghe

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id: UA-112714614-1

collections:
  tps:
    output: true
  teachings:
    output: true
  stories:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-scholar


scholar:
  bibliography_template: bib
  sort_by: year
  order: descending
  group_by: type