# Site settings
title: Benoît Verhaeghe
header-img: img/home-bg.jpg
email: benoit@badetitou.fr
copyright_name: badetitou
description: "Benoît Verhaeghe's blog"
baseurl: ""
url: "http://badetitou.github.io"
twitter_username: badetitou
github_username:  badetitou
email_username:  benoit@badetitou.fr
linkedin_username: benoitverhaeghe
orcid: 0000-0002-4588-2698
mastodon_url: https://piaille.fr/@badetitou

collections:
  tps:
    output: true
  teachings:
    output: true
  stories:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-scholar
  - jekyll-mermaid

mermaid:
  src: '/js/mermaid.min.js'
  src_config: '/js/mermaid_config.js'


scholar:
  bibliography_template: bib
  sort_by: year
  order: descending

sass:
  style: compressed
