name: Jekyll site CI

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  github-pages:

    runs-on: ubuntu-latest
    steps:
    
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
     
     # Runs a single command using the runners shell
    - name: cd on workspace
      run: cd $GITHUB_WORKSPACE

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: Jekyll Actions
      uses: helaili/jekyll-action@2.2.0
      with:
        target_branch: master
